### Register
POST http://localhost:2000/register
Content-Type: application/json

{
    "name": "heldianita andira",
    "email": "heldianitaaa@gmail.com",
    "password": "G@kpakek1"

}

### Login
POST http://localhost:2000/login
Content-Type: application/json

{
    "email": "heldianitatata@gmail.com",
    "password": "G@kpakek1"
}