### Read all Notes
GET http://localhost:2000/notes

### create a NOte
POST http://localhost:2000/notes
Content-Type: application/json

{
    "title": "malam nanti",
    "content": "main valoran habis bootcamp"
}


### Update a Note
PATCH http://localhost:2000/notes/66c6be36940b7708a6df88d1
Content-Type: application/json

{
    "title": "malam ini",
    "content": "main switch bareng isteri"
}


### Delete a Note
DELETE http://localhost:2000/notes/66c6be36940b7708a6df88d1