### Read all Notes
GET http://localhost:2000/notes

### create a NOte
POST http://localhost:2000/notes
Content-Type: application/json


{
    "title": "Minggu sore",
    "content": "nagih utang ke temen"
}


### Update a Note
PATCH http://localhost:2000/notes/66c69469f17d2ea90569725f
Content-Type: application/json

{
    "title": "Sabtu Malam",
    "content": "ngopi dan nugas"
}


### Delete a Note
DELETE http://localhost:2000/notes/