###
GET http://localhost:2000/notes

### create a NOte
POST http://localhost:2000/notes
Content-Type: application/json


{
    "title": "Selasa malam",
    "content": "membeli skin vandal"
}


### Update a Note



### Delete a Note
DELETE http://localhost:2000/notes/66c60ba99e5051cff6e4465f